name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
          cd lwtools
          make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: lwtools-unofficial-linux
        path: |
          lwtools/lwasm/lwasm
          lwtools/lwlink/lwlink
