name: win

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}    
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v4
    - name: make
      run: |
          cd lwtools
          make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: lwtools-unofficial-win
        path: |
          lwtools/lwasm/lwasm.exe
          lwtools/lwlink/lwlink.exe
